using System;
using LCAnomalyOrdeals.Defs;
using RimWorld;
using UnityEngine;
using Verse;
using Verse.Sound;

namespace LCAnomalyOrdeals.Presentation
{
    public sealed class GameComponent_WhitePresentation : GameComponent
    {
        private bool active; private string stage; private string defName; private string phase; private float elapsed;
        public GameComponent_WhitePresentation(Game game) { }
        public static void ShowStart(string stage, string defName) => Current.Game?.GetComponent<GameComponent_WhitePresentation>()?.Begin(stage, defName, "Start");
        public static void ShowEnd(string stage, string defName, bool success) => Current.Game?.GetComponent<GameComponent_WhitePresentation>()?.Begin(stage, defName, success ? "Success" : "Failure");
        public static void FilterCurrentInput() { GameComponent_WhitePresentation component = Current.Game?.GetComponent<GameComponent_WhitePresentation>(); if (component == null || !component.active || component.elapsed >= Examinations.WhiteOrdealWorker.ActiveSettings(component.defName).presentationInputBlockSeconds || Event.current == null || Event.current.type == EventType.Layout || Event.current.type == EventType.Repaint) return; Event.current.Use(); }
        public override void GameComponentUpdate() { if (!active) return; WhiteOrdealSettings settings = Examinations.WhiteOrdealWorker.ActiveSettings(defName); elapsed += Time.unscaledDeltaTime; if (elapsed >= settings.presentationFadeInSeconds + settings.presentationHoldSeconds + settings.presentationFadeOutSeconds) active = false; }
        public override void GameComponentOnGUI() { if (!active || Event.current == null) return; try { WhiteOrdealSettings settings = Examinations.WhiteOrdealWorker.ActiveSettings(defName); WhiteOrdealPresentation presentation = settings.PresentationFor(stage); if (presentation == null) { active = false; return; } if (elapsed < settings.presentationInputBlockSeconds && Event.current.type != EventType.Layout && Event.current.type != EventType.Repaint) Event.current.Use(); if (Event.current.type == EventType.Repaint) Draw(settings, presentation); } catch (Exception exception) { active = false; Log.ErrorOnce("[LC Anomaly Ordeals] White presentation failed safely: " + exception, 198604275); } }
        public override void ExposeData() { Scribe_Values.Look(ref active, "LCOrdealWhitePresentationActive", false); Scribe_Values.Look(ref stage, "LCOrdealWhitePresentationStage"); Scribe_Values.Look(ref defName, "LCOrdealWhitePresentationDef"); Scribe_Values.Look(ref phase, "LCOrdealWhitePresentationPhase"); Scribe_Values.Look(ref elapsed, "LCOrdealWhitePresentationElapsed", 0f); }
        private void Begin(string value, string definition, string presentationPhase) { WhiteOrdealPresentation presentation = Examinations.WhiteOrdealWorker.ActiveSettings(definition).PresentationFor(value); if (presentation == null) return; stage = value; defName = definition; phase = presentationPhase; elapsed = 0f; active = true; (phase == "Success" ? presentation.successSound : phase == "Failure" ? presentation.failureSound : presentation.startSound)?.PlayOneShotOnCamera(); }
        private void Draw(WhiteOrdealSettings settings, WhiteOrdealPresentation presentation)
        {
            float alpha = Alpha(settings); Color accent = presentation.color.ToColor; Rect screen = new Rect(0f, 0f, UI.screenWidth, UI.screenHeight); Widgets.DrawBoxSolid(screen, new Color(0f, 0f, 0f, settings.presentationOverlayAlpha * alpha)); float height = Mathf.Clamp(UI.screenHeight * 0.36f, 240f, 410f); Rect band = new Rect(0f, (UI.screenHeight - height) / 2f, UI.screenWidth, height); Widgets.DrawBoxSolid(band, new Color(accent.r, accent.g, accent.b, settings.presentationBandAlpha * alpha)); Widgets.DrawBoxSolid(new Rect(0f, band.y, UI.screenWidth, 4f), new Color(accent.r, accent.g, accent.b, alpha)); Widgets.DrawBoxSolid(new Rect(0f, band.yMax - 4f, UI.screenWidth, 4f), new Color(accent.r, accent.g, accent.b, alpha));
            string kicker = (phase == "Success" ? "LCOrdeal_PresentationSuppressed" : phase == "Failure" ? "LCOrdeal_PresentationFailed" : "LCOrdeal_PresentationWhite" + stage).Translate(); string title = (phase == "Success" ? presentation.successTitleKey : phase == "Failure" ? presentation.failureTitleKey : presentation.startTitleKey).Translate(); string body = (phase == "Success" ? presentation.successTextKey : phase == "Failure" ? presentation.failureTextKey : presentation.startTextKey).Translate();
            Color oldColor = GUI.color; TextAnchor oldAnchor = Text.Anchor; GameFont oldFont = Text.Font; GUI.color = new Color(1f, 1f, 1f, alpha); Text.Anchor = TextAnchor.MiddleCenter; GUIStyle kickerStyle = new GUIStyle(Text.CurFontStyle) { alignment = TextAnchor.MiddleCenter, fontSize = Mathf.Clamp(Mathf.RoundToInt(UI.screenHeight * 0.027f), 19, 32), fontStyle = FontStyle.Bold }; GUI.Label(new Rect(80f, band.y + 24f, UI.screenWidth - 160f, 46f), kicker, kickerStyle); GUIStyle titleStyle = new GUIStyle(Text.CurFontStyle) { alignment = TextAnchor.MiddleCenter, fontSize = Mathf.Clamp(Mathf.RoundToInt(UI.screenHeight * 0.06f), 36, 72), fontStyle = FontStyle.Bold }; GUI.Label(new Rect(80f, band.y + 70f, UI.screenWidth - 160f, 104f), title, titleStyle); Text.Font = GameFont.Small; GUI.Label(new Rect(UI.screenWidth * 0.16f, band.y + 172f, UI.screenWidth * 0.68f, height - 194f), body, Text.CurFontStyle); GUI.color = oldColor; Text.Anchor = oldAnchor; Text.Font = oldFont;
        }
        private float Alpha(WhiteOrdealSettings settings) { if (settings.presentationFadeInSeconds > 0f && elapsed < settings.presentationFadeInSeconds) return Mathf.Clamp01(elapsed / settings.presentationFadeInSeconds); float start = settings.presentationFadeInSeconds + settings.presentationHoldSeconds; return settings.presentationFadeOutSeconds > 0f && elapsed > start ? 1f - Mathf.Clamp01((elapsed - start) / settings.presentationFadeOutSeconds) : 1f; }
    }
}
